### ISSUE TITLE
Ayuda 

### ISSUE THREAD

**Issue by brayang091** [sharklatan/SharkGo#3]
Nesecito ayuda con el shark go me sale esto cuando le doy a "set fake location" ----------> Unable to mount developer image.
![Captura web_23-9-2023_12759_sharkgo sharklatan com](https://github.com/sharklatan/SharkGo/assets/145829491/27f359ce-38d6-4b8d-950d-f39c562c318a)

**Comment by clinton2111** [comment]
What iOS version are you running?

**Comment by brayang091** [comment]
iOS 16.5.1

**Comment by brayang091** [comment]
ALGUNA SOLUCION QUE ME PUEDEN DAR ?

**Comment by sharklatan** [comment]
> Nesecito ayuda con el shark go me sale esto cuando le doy a "set fake location" ----------> Unable to mount developer image. ![Captura web_23-9-2023_12759_sharkgo sharklatan com](https://user-images.githubusercontent.com/145829491/270091230-27f359ce-38d6-4b8d-950d-f39c562c318a.jpeg)



> iOS 16.5.1


> ALGUNA SOLUCION QUE ME PUEDEN DAR ?


 Por favor, ¿puedes compartir una captura de la carpeta 📂 donde instalaste SharkGo? El directorio por defecto es:

`C:\Program Files (x86)\SharkGo\DeveloperImages\`

Dentro de esta ubicación, deberías encontrar una carpeta 📁 correspondiente a tu versión de iOS, que en este caso es 16.5.1. Estoy aquí para ayudarte a resolver cualquier problema que puedas tener. Para hacerlo, necesitaré ver cuál es el error. Es posible que se deba a una imagen que no es compatible, está mal enlazada o no se descargó correctamente.

**Comment by brayang091** [comment]
Esto me sale 
![image](https://github.com/sharklatan/SharkGo/assets/145829491/354aa7d6-5c90-41d4-922c-0c7466e8104d)

**Comment by brayang091** [comment]
Dentro de la carpeta me sale esto 
![image](https://github.com/sharklatan/SharkGo/assets/145829491/2da04aba-d9d6-4e9e-9116-e719639ef9ae)

**Comment by sharklatan** [comment]
> Esto me sale ![image](https://user-images.githubusercontent.com/145829491/270178159-354aa7d6-5c90-41d4-922c-0c7466e8104d.png)

Intenta cambiarle el nombre a la carpeta a 16.5.1 para que coincida con tu versión

**Comment by sharklatan** [comment]
16.5.1 al ser un update de 16.5 Utilizan el mismo archivo. Algo similar sucede con 14.8.1 que utiliza los mismos archivos 14.8.

revisare porque no se hace automáticamente ya que si está especificado en el código que lo haga. 

Así que la solución sería cambiar la carpeta 📁 para que coincida con la versión que tienes instalada.
