### ISSUE TITLE
Como ser fly en ios pokemon go y mh now 

### ISSUE THREAD

**Issue by Jordynad1** [sharklatan/SharkGo#4]
Hola amigos soy creador de contenido no  funciona para ios 16.7 no soporta podras resolverlo bro tendra soporte para ios 17 esta brutal el programa  espero  lo sigas dando soporte mi canal si gustas pasar es jordy nad

**Comment by sharklatan** [comment]
Se añadió soporte para iOS 16.7 y 16.7.1 ya debería funcionarte 

Sobre **iOS 17** no habrá soporte hasta que la librería **libimobiledevice**  se actualice correctamente, aunque hay solución alternativa usando otra librería **pymobiledevice3** es solo para MacOS por lo cual Windows no está aún funcionando.

Sigo de cerca el STATUS actual de la librería [libimobiledevice ](https://github.com/libimobiledevice/libimobiledevice/issues/1490)  pero aún no hay nada claro, igualmente puedes comprobar que ninguno de los programas tanto de paga o gratuitos como **3uTools** tienen soporte para **iOS 17** en **Windows** , solo resta esperar ante posibles actualizaciones.
