### ISSUE TITLE
AYUDA 2.0

### ISSUE THREAD

**Issue by brayang091** [sharklatan/SharkGo#5]
Ya se me habia solucionado pero hoy ya no me dejaba cambiarle el nombre a la version y salian las 2 carpetas 
![image](https://github.com/sharklatan/SharkGo/assets/145829491/564eba86-459c-472c-bc6e-0d487b2be0cb)

**Comment by sharklatan** [comment]
Dentro de la carpeta solo debes tener los mismos archivos, con que los tengas ya debería funcionar, **SharkGo** no está programado para eliminar esas carpetas solo descargarlas y descomprimirlo, por lo cual mientras tengas archivos dentro de la debería funcionar
