### ISSUE TITLE
Problema de instalación 

### ISSUE THREAD

**Issue by abece280390** [sharklatan/SharkGo#6]
![IMG_3067](https://github.com/sharklatan/SharkGo/assets/148215672/dd1fe23b-b26e-4853-bc3f-0251bba81347)

hola,estoy siguiendo tu tutorial,pero ala hora de entrar en tu página y darle a download me habré la siguiente pagina que te adjunto en la foto, cómo Sitio no seguro cutsy.net y seguido sharkgo,haver si puedes ayudarme gracias.

**Comment by sharklatan** [comment]
> ![IMG_3067](https://github.com/sharklatan/SharkGo/assets/148215672/dd1fe23b-b26e-4853-bc3f-0251bba81347)
> 
> 
> 
> hola,estoy siguiendo tu tutorial,pero ala hora de entrar en tu página y darle a download me habré la siguiente pagina que te adjunto en la foto, cómo Sitio no seguro cutsy.net y seguido sharkgo,haver si puedes ayudarme gracias.
> 
> 

Hola,

Gracias por tu interés en **SharkGo**. Entendemos que estás experimentando problemas para descargarlo debido al mensaje de "_página no segura_". Queremos explicarte que utilizamos un acortador de enlaces para generar ingresos necesarios para mantener el servicio en funcionamiento. Estos ingresos se utilizan para cubrir los costos de servidores, dominios, hosting y otros gastos asociados con el mantenimiento del servicio. Los dominios y servidores tienen un costo, y el acortador nos ayuda a cubrir estos gastos.

Aunque el proyecto es gratuito y tenemos más de 5,000 usuarios activos, hasta ahora no hemos recibido absolutamente ninguna donación. Las donaciones son una alternativa importante para generar los ingresos necesarios. Entendemos que algunas personas bloquean la publicidad, lo que dificulta la generación de ingresos por ese medio.

Nuestra meta es seguir siendo gratuitos para los usuarios mientras cubrimos los costos de los servicios.

Mientras tanto, para solucionar el problema de descarga, te recomendamos intentar abrir el enlace desde otro navegador o en modo incógnito para evitar las interferencias de las extensiones del navegador durante la descarga. Ten en cuenta que algunos antivirus también podrían interferir con la descarga del archivo.

Agradecemos profundamente tu comprensión y apoyo en nuestra misión de mantener el servicio gratuito y accesible para todos.

Saludos,
Shark
