### ISSUE TITLE
Incompatibilidad con iOS 15.8

### ISSUE THREAD

**Issue by Doomstake** [sharklatan/SharkGo#7]
Hola ¿qué tal?

Había estado usando el SharkGo en mi iPhone 6S, operando con el iOS 15.7 sin ningún problema, pero se actualizó a la versión 15.8 que salió el 22 de octubre y al usar el SharkGo me dice que esta versión de iOS no tiene soporte en este momento. Te adjunto las capturas de pantalla confirmando la iOS actual del celular y el mensaje de error que aparece.

Muchas gracias por esta herramienta tan útil para jugar Pokémon Go sin riesgos.

![ss2](https://github.com/sharklatan/SharkGo/assets/152532089/99496b48-234b-4b5e-baca-739ff291117a)
![ss](https://github.com/sharklatan/SharkGo/assets/152532089/ae263ceb-bf99-4204-ac2a-f1edd3394b20)

**Comment by sharklatan** [comment]
Aprecio tu reporte. Gracias a tu observación, he identificado el problema y se ha [incorporado soporte para las versiones 15.7.2 hasta 15.8. ](https://github.com/sharklatan/SharkGo/commit/5a6bf7d98cf5a409298c253fa84a97d65bc0dbe6)

¡Tu contribución fue fundamental!

**Comment by Doomstake** [comment]
> Aprecio tu reporte. Gracias a tu observación, he identificado el problema y se ha [incorporado soporte para las versiones 15.7.2 hasta 15.8. ](https://github.com/sharklatan/SharkGo/commit/5a6bf7d98cf5a409298c253fa84a97d65bc0dbe6)
> 
> ¡Tu contribución fue fundamental!

¡Gracias a ti! Acabo de ensayarlo y está arrojando este mensaje de error.

![1](https://github.com/sharklatan/SharkGo/assets/152532089/cf2c545e-0d79-4ed8-b88b-640a156a3b87)
