### ISSUE TITLE
iOS 15.8 - Mount failed with status: N/A and error: ImageMountFailed #8

### ISSUE THREAD

**Issue by GoKevinn** [sharklatan/SharkGo#9]
Buen día, tengo este error al intentar inciar la aplicación, tengo IOS 15.8.
![1](https://github.com/sharklatan/SharkGo/assets/153246544/3c9ede35-dff1-4ecc-9775-0cafcaa7fe24)

**Comment by sharklatan** [comment]
Hola @GoKevinn gracias por tu reporte,

Te confirmo que tengo añadido el soporte para 15.8 y no debería salir ese error:
![image](https://github.com/sharklatan/SharkGo/assets/5210221/27b142f4-a17a-4a1d-bd82-8309207564f6)



El error podría deberse un error en tu instalación
no tengo ningún dispositivo en esta versión para comprobarlo, pero con gusto te doy los pasos para que te funcione en esa versión de iOS


1.- ve a tu carpera donde instalaste SharkGo

`C:\Program Files (x86)\SharkGo\`


2.- Dentro encontaras una carpeta llamada **DeveloperImages**, dentro de ella y encontraras unas carpetas con referencia a las versiones de iOS

![image](https://github.com/sharklatan/SharkGo/assets/5210221/cc789463-bef4-460a-8ea7-d9a04d80c085)


3.- Si tienes una carpeta de iOS 15.7.x cópiala a tu escritorio, luego cámbiale el nombre a 15.8 y regrésala a la carpeta **DeveloperImages**



4.- Si no tienes ninguna carpeta de 15.7 (15.71 , 15.7.2 etc), 15 créala y pega dentro coloca estos archivos. 

![image](https://github.com/sharklatan/SharkGo/assets/5210221/bb36b94c-9405-4e41-ac8b-d7a5de6cb236)

Los archivos los descargas desde aqui [15.7.zip](https://github.com/mspvirajpatel/Xcode_Developer_Disk_Images/releases/download/15.7/15.7.zip)


Te debe quedar algo así:

![image](https://github.com/sharklatan/SharkGo/assets/5210221/8e013f5e-5442-404e-a157-4ae1bb2932e4)


Cierra y abre nuevamente SharkGo y me dices si funciono

Saludos ;)

**Comment by GoKevinn** [comment]
Hola Sharklatan/Sharkgo la verdad intenté tal cual como lo comentas en la
respuesta y sigue apareciendo el mismo error, descargué la carpeta de nuevo
y cambié el nombre y nada la verdad. No sé qué suceda, quedo atento a
cualquier otra sugerencia.

**Comment by sharklatan** [comment]
Adjúntame foto de la carpeta y lo que sale en la ventana de SharkGo

**Comment by GoKevinn** [comment]
Hola!!! prendí el PC para enviarte las fotos y me encontré con la genial
sorpresa de que ya funciona jajaja mil gracias

**Comment by Doomstake** [comment]
Hola! Hermano, qué pena molestarte tanto con esto, pero no ha sido posible. 

Intenté paso a paso el método mencionado previamente, descargué la carpeta, descomprimí los archivos y los puse tal cual como en la imagen y reinicié, pero nada, luego decidí reinstalar y repetir los pasos y nada aún, persiste el mismo error. 

No sé si tenga algo que ver, pero los archivos que muestras dentro de la carpeta 15.8 en tu imagen tienen un peso diferente a los que están dentro de la carpeta que adjuntaste para descargar, la 15.7.

Te adjunto imágenes de las carpetas, el Sharkgo y el error que me arroja:
![1](https://github.com/sharklatan/SharkGo/assets/152532089/a2f15f57-09de-45c8-83d8-1220a286c467)
![2](https://github.com/sharklatan/SharkGo/assets/152532089/4000c168-995d-4544-9626-11107aca1b9c)
![3](https://github.com/sharklatan/SharkGo/assets/152532089/52e048d8-9484-475a-a70a-6ce0212c3e9b)
![4](https://github.com/sharklatan/SharkGo/assets/152532089/474da355-248a-42ae-8587-14dc129f8c55)
![5](https://github.com/sharklatan/SharkGo/assets/152532089/2aa60b61-9951-49eb-aa05-ade94a551d1e)

**Comment by GoKevinn** [comment]
Hola Doomstake, lo que yo realicé fue desinstalar el programa desde el panel de control y posterior mente ir a la carpeta creada en program files y eliminar los archivos residuales, posteriormente reinicié mi teléfono y realicé nuevamente la instalación, con la diferencia que la carpeta de las imágenes la remplacé por la que Luis compartió anterior mente y realicé el proceso de cambio de nombre y dejé los dos archivos, dejé el archivo 15.7 y 15.8. Posterior reinicié la computadora.

**Comment by Doomstake** [comment]
> Hola Doomstake, lo que yo realicé fue desinstalar el programa desde el panel de control y posterior mente ir a la carpeta creada en program files y eliminar los archivos residuales, posteriormente reinicié mi teléfono y realicé nuevamente la instalación, con la diferencia que la carpeta de las imágenes la remplacé por la que Luis compartió anterior mente y realicé el proceso de cambio de nombre y dejé los dos archivos, dejé el archivo 15.7 y 15.8. Posterior reinicié la computadora.

Hola, GoKevinn, la verdad he intentado de todo, hasta restauré el iPhone y nada ha funcionado, no sé si estoy haciendo algo mal. Intenté seguir todos los pasos al pie de la letra y no ha sido posible, me continúa arrojando el mismo error.
